-- AlterTable
ALTER TABLE "Asset" ALTER COLUMN "dateLaunched" DROP NOT NULL,
ALTER COLUMN "marketCapUSD" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Chain" ALTER COLUMN "dateLaunched" DROP NOT NULL,
ALTER COLUMN "marketCapUSD" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Platform" ALTER COLUMN "tvlUSD" DROP NOT NULL,
ALTER COLUMN "dateLaunched" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Pool" ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "tvlUSD" DROP NOT NULL,
ALTER COLUMN "dateLaunched" DROP NOT NULL;
